export enum LanguageEnum {
  Abkhazian,
  Afar,
  Afrikaans,
  Akan,
  Albanian,
  Amharic,
  Arabic,
  Aragonese,
  Armenian,
  Assamese,
  Avaric,
  Avestan,
  Aymara,
  Azerbaijani,
  Bambara,
  Bashkir,
  Basque,
  Belarusian,
  Bengali,
  BihariLanguages,
  Bislama,
  Bosnian,
  Breton,
  Bulgarian,
  Burmese,
  CatalanValencian,
  CentralKhmer,
  Chamorro,
  Chechen,
  ChichewaChewaNyanja,
  Chinese,
  ChurchSlavonicOldBulgarianOldChurchSlavonic,
  Chuvash,
  Cornish,
  Corsican,
  Cree,
  Croatian,
  Czech,
  Danish,
  DivehiDhivehiMaldivian,
  Dutch,
  Dzongkha,
  English,
  Esperanto,
  Estonian,
  Ewe,
  Faroese,
  Fijian,
  Finnish,
  French,
  Fulah,
  GaelicScottishGaelic,
  Galician,
  Ganda,
  Georgian,
  German,
  GikuyuKikuyu,
  Greek,
  GreenlandicKalaallisut,
  Guarani,
  Gujarati,
  HaitianCreole,
  Hausa,
  Hebrew,
  Herero,
  Hindi,
  HiriMotu,
  Hungarian,
  Icelandic,
  Ido,
  Igbo,
  Indonesian,
  InterlinguaInternationalAuxiliaryLanguageAssociation,
  Interlingue,
  Inuktitut,
  Inupiaq,
  Irish,
  Italian,
  Japanese,
  Javanese,
  Kannada,
  Kanuri,
  Kashmiri,
  Kazakh,
  Kinyarwanda,
  Komi,
  Kongo,
  Korean,
  KwanyamaKuanyama,
  Kurdish,
  Kyrgyz,
  Lao,
  Latin,
  Latvian,
  LetzeburgeschLuxembourgish,
  LimburgishLimburganLimburger,
  Lingala,
  Lithuanian,
  LubaKatanga,
  Macedonian,
  Malagasy,
  Malay,
  Malayalam,
  Maltese,
  Manx,
  Maori,
  Marathi,
  Marshallese,
  Romanian,
  Mongolian,
  Nauru,
  NavajoNavaho,
  NorthernNdebele,
  Ndonga,
  Nepali,
  NorthernSami,
  Norwegian,
  NorwegianBokmal,
  NorwegianNynorsk,
  NuosuSichuanYi,
  OccitanPost1500,
  Ojibwa,
  Oriya,
  Oromo,
  OssetianOssetic,
  Pali,
  PanjabiPunjabi,
  PashtoPushto,
  Persian,
  Polish,
  Portuguese,
  Quechua,
  Romansh,
  Rundi,
  Russian,
  Samoan,
  Sango,
  Sanskrit,
  Sardinian,
  Serbian,
  Shona,
  Sindhi,
  Sinhala,
  Slovak,
  Slovenian,
  Somali,
  SothoSouthern,
  SouthNdebele,
  Spanish,
  Sundanese,
  Swahili,
  Swati,
  Swedish,
  Tagalog,
  Tahitian,
  Tajik,
  Tamil,
  Tatar,
  Telugu,
  Thai,
  Tibetan,
  Tigrinya,
  TongaTongaIslands,
  Tsonga,
  Tswana,
  Turkish,
  Turkmen,
  Twi,
  UighurUyghur,
  Ukrainian,
  Urdu,
  Uzbek,
  Venda,
  Vietnamese,
  Volapuk,
  Walloon,
  Welsh,
  WesternFrisian,
  Wolof,
  Xhosa,
  Yiddish,
  Yoruba,
  ZhuangChuang,
  Zulu,
}

export const Languages = [
  {
    id: LanguageEnum.Arabic,
    titleEn: "Arabic",
    titleAr: "العربية",
  },
  {
    id: LanguageEnum.English,
    titleEn: "English",
    titleAr: "الإنجليزية",
  },
  {
    id: LanguageEnum.Spanish,
    titleEn: "Spanish",
    titleAr: "الإسبانية",
  },
  {
    id: LanguageEnum.French,
    titleEn: "French",
    titleAr: "الفرنسية",
  },
  {
    id: LanguageEnum.German,
    titleEn: "German",
    titleAr: "الألمانية",
  },
  {
    id: LanguageEnum.Italian,
    titleEn: "Italian",
    titleAr: "الإيطالية",
  },
  {
    id: LanguageEnum.Portuguese,
    titleEn: "Portuguese",
    titleAr: "البرتغالية",
  },
  {
    id: LanguageEnum.Russian,
    titleEn: "Russian",
    titleAr: "الروسية",
  },
  {
    id: LanguageEnum.Chinese,
    titleEn: "Chinese",
    titleAr: "الصينية",
  },
  {
    id: LanguageEnum.Japanese,
    titleEn: "Japanese",
    titleAr: "اليابانية",
  },
  {
    id: LanguageEnum.Korean,
    titleEn: "Korean",
    titleAr: "الكورية",
  },
  {
    id: LanguageEnum.Hindi,
    titleEn: "Hindi",
    titleAr: "الهندية",
  },
  {
    id: LanguageEnum.Bengali,
    titleEn: "Bengali",
    titleAr: "البنغالية",
  },
  {
    id: LanguageEnum.Turkish,
    titleEn: "Turkish",
    titleAr: "التركية",
  },
  {
    id: LanguageEnum.Dutch,
    titleEn: "Dutch",
    titleAr: "الهولندية",
  },
  {
    id: LanguageEnum.Swedish,
    titleEn: "Swedish",
    titleAr: "السويدية",
  },
  {
    id: LanguageEnum.Polish,
    titleEn: "Polish",
    titleAr: "البولندية",
  },
  {
    id: LanguageEnum.Ukrainian,
    titleEn: "Ukrainian",
    titleAr: "الأوكرانية",
  },
  {
    id: LanguageEnum.Czech,
    titleEn: "Czech",
    titleAr: "التشيكية",
  },
  {
    id: LanguageEnum.Greek,
    titleEn: "Greek",
    titleAr: "اليونانية",
  },
  {
    id: LanguageEnum.Hebrew,
    titleEn: "Hebrew",
    titleAr: "العبرية",
  },
  {
    id: LanguageEnum.Hungarian,
    titleEn: "Hungarian",
    titleAr: "المجرية",
  },
  {
    id: LanguageEnum.Indonesian,
    titleEn: "Indonesian",
    titleAr: "الأندونيسية",
  },
  {
    id: LanguageEnum.Vietnamese,
    titleEn: "Vietnamese",
    titleAr: "الفيتنامية",
  },
  {
    id: LanguageEnum.Thai,
    titleEn: "Thai",
    titleAr: "التايلاندية",
  },
  {
    id: LanguageEnum.Swahili,
    titleEn: "Swahili",
    titleAr: "السواحيلية",
  },
  {
    id: LanguageEnum.Afrikaans,
    titleEn: "Afrikaans",
    titleAr: "الأفريكانية",
  },
  {
    id: LanguageEnum.Finnish,
    titleEn: "Finnish",
    titleAr: "الفنلندية",
  },
  {
    id: LanguageEnum.Danish,
    titleEn: "Danish",
    titleAr: "الدانماركية",
  },
  {
    id: LanguageEnum.Norwegian,
    titleEn: "Norwegian",
    titleAr: "النرويجية",
  },
  {
    id: LanguageEnum.Romanian,
    titleEn: "Romanian",
    titleAr: "الرومانية",
  },
  {
    id: LanguageEnum.Slovak,
    titleEn: "Slovak",
    titleAr: "السلوفاكية",
  },
  {
    id: LanguageEnum.Slovenian,
    titleEn: "Slovenian",
    titleAr: "السلوفينية",
  },
  {
    id: LanguageEnum.Croatian,
    titleEn: "Croatian",
    titleAr: "الكرواتية",
  },
  {
    id: LanguageEnum.Bulgarian,
    titleEn: "Bulgarian",
    titleAr: "البلغارية",
  },
  {
    id: LanguageEnum.Lithuanian,
    titleEn: "Lithuanian",
    titleAr: "اللتوانية",
  },
  {
    id: LanguageEnum.Latvian,
    titleEn: "Latvian",
    titleAr: "اللاتفية",
  },
  {
    id: LanguageEnum.Estonian,
    titleEn: "Estonian",
    titleAr: "الإستونية",
  },
  {
    id: LanguageEnum.Malay,
    titleEn: "Malay",
    titleAr: "الماليزية",
  },
  {
    id: LanguageEnum.HaitianCreole,
    titleEn: "Haitian Creole",
    titleAr: "الكريول الهايتي",
  },
  {
    id: LanguageEnum.Urdu,
    titleEn: "Urdu",
    titleAr: "الأردية",
  },
  {
    id: LanguageEnum.Serbian,
    titleEn: "Serbian",
    titleAr: "الصربية",
  },
  {
    id: LanguageEnum.Bosnian,
    titleEn: "Bosnian",
    titleAr: "البوسنية",
  },
  {
    id: LanguageEnum.Albanian,
    titleEn: "Albanian",
    titleAr: "الألبانية",
  },
  {
    id: LanguageEnum.Macedonian,
    titleEn: "Macedonian",
    titleAr: "المقدونية",
  },
  {
    id: LanguageEnum.Icelandic,
    titleEn: "Icelandic",
    titleAr: "الآيسلندية",
  },
  {
    id: LanguageEnum.Mongolian,
    titleEn: "Mongolian",
    titleAr: "المنغولية",
  },
  {
    id: LanguageEnum.Gujarati,
    titleEn: "Gujarati",
    titleAr: "الغوجاراتية",
  },
  {
    id: LanguageEnum.Tamil,
    titleEn: "Tamil",
    titleAr: "التاميلية",
  },
  {
    id: LanguageEnum.Telugu,
    titleEn: "Telugu",
    titleAr: "التيلجو",
  },
  {
    id: LanguageEnum.Kannada,
    titleEn: "Kannada",
    titleAr: "الكانادية",
  },
  {
    id: LanguageEnum.Marathi,
    titleEn: "Marathi",
    titleAr: "الماراثية",
  },
  {
    id: LanguageEnum.Malayalam,
    titleEn: "Malayalam",
    titleAr: "المالايالامية",
  },
  {
    id: LanguageEnum.Sinhala,
    titleEn: "Sinhala",
    titleAr: "السينهالية",
  },
  {
    id: LanguageEnum.Nepali,
    titleEn: "Nepali",
    titleAr: "النيبالية",
  },
];

const getLanguagesOptions = () => {
  return Languages.map((i) => ({
    name: i.titleAr + " | " + i.titleEn,
    value: i.id,
  }));
};

export const LanguagesOptions = getLanguagesOptions();
