import Navigation from "@/components/Navigation";
import UIContext from "@/contexts/UIContext";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UIContext>
        {/* <Navigation /> */}
        <body className={inter.className}>{children}</body>
      </UIContext>
    </html>
  );
}
